{
 "title": "FlareSolverr",
 "description": "A dashboard for the FlareSolverr Prometheus exporter: https://github.com/FlareSolverr/FlareSolverr",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(flaresolverr_request_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Challenges",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\", result=\"solved\"})",
     "legendFormat": "Solved"
    },
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\", result=\"not_detected\"})",
     "legendFormat": "Not Detected"
    },
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\", result=\"error\"})",
     "legendFormat": "Not Solved"
    }
   ]
  },
  {
   "title": "Challenges Solved",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_total{result=\"solved\"})"
    }
   ]
  },
  {
   "title": "Challenges Not Detected",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_total{result=\"not_detected\"})"
    }
   ]
  },
  {
   "title": "Challenges Not Solved",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_total{result=\"error\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\"}) by (domain)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_duration_sum{instance=\"$host\"} / flaresolverr_request_duration_count{instance=\"$host\"}) by (domain)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\", result=\"solved\"}) by (domain)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\", result=\"not_detected\"}) by (domain)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flaresolverr_request_total{instance=\"$host\", result=\"error\"}) by (domain)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}