apiVersion: v1
kind: Namespace
metadata:
  name: emqx-operator-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emqx-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: emqx-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: emqx-operator
    targetRevision: 2.2.25
    repoURL: https://repos.emqx.io/charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
