apiVersion: v1
kind: Namespace
metadata:
  name: falco-system
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: falco-secrets-infisical
  namespace: falco-system
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: cluster-secrets-rgq1
        envSlug: dev
        secretsPath: /falco
        recursive: true
      credentialsRef:
        secretName: infisical-machine-id
        secretNamespace: infisical
  managedSecretReference:
    secretName: falco-secrets
    secretNamespace: falco-system
    creationPolicy: Owner
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: falco-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: falco
    targetRevision: 7.1.1
    repoURL: https://falcosecurity.github.io/charts
    helm:
      valuesObject:
        serviceMonitor:
          create: true
        metrics:
          enabled: true
        collectors:
          containerd:
            socket: /run/k3s/containerd/containerd.sock
        falcosidekick:
          enabled: true
          config:
            existingSecret: falco-secrets
          serviceMonitor:
            enabled: true
          prometheusRules:
            enabled: true
          webui:
            enabled: true
            disableauth: true
        customRules:
          shut-the-fuck-up.yaml: |
            - list: trusted_k8s_api_container_images
              items:
                - quay.io/argoproj/argocd
                - registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
                - ghcr.io/kyverno/reports-controller
                - ghcr.io/kyverno/cleanup-controller
                - ghcr.io/kyverno/kyverno
                - ghcr.io/tensorchord/cloudnative-pgvecto.rs
                - docker.io/bitnami/kubectl
                - docker.elastic.co/eck/eck-operator
                - ghcr.io/kedacore/keda
                - docker.io/infisical/kubernetes-operator
                - docker.io/bitnami/rabbitmq-cluster-operator
                - registry.k8s.io/kube-state-metrics/kube-state-metrics
                - docker.io/longhornio/longhorn-manager
                - ghcr.io/kyverno/background-controller
                - quay.io/kiwigrid/k8s-sidecar
                - ghcr.io/cloudnative-pg/cloudnative-pg
                - ghcr.io/goauthentik/server
                - docker.io/longhornio/csi-attacher
                - docker.elastic.co/beats/filebeat
                - ghcr.io/cloudnative-pg/pgbouncer
                - ghcr.io/stakater/reloader
                - ghcr.io/brunostjohn/refund-bot
                - docker.io/longhornio/longhorn-instance-manager
            - macro: user_known_contact_k8s_api_server_activities
              condition: or container.image.repository in (trusted_k8s_api_container_images)
              override:
                condition: append
            - list: trusted_proc_names
              items:
                - postgres
            - macro: user_shell_container_exclusions
              condition: or (container.image.repository in (trusted_k8s_api_container_images) and proc.pname in (trusted_proc_names))
              override:
                condition: append
            - list: known_drop_and_execute_containers
              items:
                - ghcr.io/flaresolverr/flaresolverr
                - ghcr.io/toeverything/affine-graphql
                - docker.io/crocodilestick/calibre-web-automated
                - docker.io/longhornio/longhorn-instance-manager
                - ghcr.io/haveagitgat/tdarr
                - ghcr.io/haveagitgat/tdarr_node
                - docker.io/thijsvanloef/palworld-server-docker
              override:
                items: append
            - list: known_clear_log_cmd
              items:
                - containerd
            - list: known_clear_log_pname
              items:
                - k3s-agent
                - k3s-server
            - list: known_clear_log_containers
              items:
                - docker.io/longhornio/longhorn-instance-manager
            - macro: allowed_clear_log_files
              condition: or ((proc.name in (known_clear_log_cmd) and proc.pname in (known_clear_log_pname)) or container.image.repository in (known_clear_log_containers))
              override:
                condition: append

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
