apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentinel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis
    targetRevision: 20.6.0
    repoURL: registry-1.docker.io/bitnamicharts
    helm:
      valuesObject:
        auth:
          password: redis
        architecture: replication
        master:
          configuration: |
            databases 32
          persistence:
            storageClass: longhorn-unreplicated
        rbac:
          create: true
        serviceAccount:
          create: true
          automountServiceAccountToken: true
        replica:
          configuration: |
            databases 32
          replicaCount: 3
          persistence:
            storageClass: longhorn-unreplicated
          automountServiceAccountToken: true
        sentinel:
          enabled: true
          persistence:
            enabled: true
            storageClass: longhorn-unreplicated
          masterService:
            enabled: true
        metrics:
          enabled: true
          podMonitor:
            enabled: true
          serviceMontior:
            enabled: true
        tls:
          enabled: true
          existingSecret: redis-tls
          certFilename: tls.crt
          certKeyFilename: tls.key
          certCAFilename: ca.crt
        networkPolicy:
          enabled: true
          allowExternal: false
          allowExternalEgress: false
          ingressNSPodMatchLabels:
            redis-sentinel: "true"
          metrics:
            extraArgs:
              skip-tls-verification: "true"
            allowExternal: false
            ingressNSMatchLabels:
              kubernetes.io/metadata.name: monitoring
            ingressNSPodMatchLabels:
              app.kubernetes.io/name: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
