apiVersion: v1
kind: ConfigMap
metadata:
  name: modded-mc-config
  namespace: game-servers
data:
  EULA: "true"
  TZ: Europe/Dublin
  JVM_XX_OPTS: "-XX:+UseZGC"
  JVM_OPTS: "-Xlog:gc*,safepoint:file=/data/logs/gc.log:time,uptime,level,tags:filecount=5,filesize=20M -Dchunksmith.maxWorkingCount=1"
  BACKGROUND_PREGEN_CAMPAIGN: nether-end-256c-v1
  RCON_CMDS_FIRST_CONNECT: "cs pause"
  RCON_CMDS_PERIOD: "2"
  INIT_MEMORY: 8G
  MAX_MEMORY: 16G
  TYPE: NEOFORGE
  VERSION: "26.1.2"
  NEOFORGE_VERSION: "26.1.2.94"
  ONLINE_MODE: "false"
  MOTD: "§4D§2U§3S§5T§6E§7R§9M§aA§bX§cX§dE§eR §f§lCENTRAL"
  ICON: https://homepage-assets.static.zefirsroyal.cloud/kitty.png
  MAX_PLAYERS: "10"
  SERVER_NAME: "Zefir's Central"
  ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
  ALLOW_FLIGHT: "true"
  CURSEFORGE_FILES: |
    https://www.curseforge.com/minecraft/mc-mods/distant-horizons
    https://www.curseforge.com/minecraft/mc-mods/ferritecore
    https://www.curseforge.com/minecraft/mc-mods/tree-harvester
    https://www.curseforge.com/minecraft/mc-mods/lithium
    https://www.curseforge.com/minecraft/mc-mods/journeymap
    https://www.curseforge.com/minecraft/mc-mods/collective
    https://www.curseforge.com/minecraft/mc-mods/bluemap
    https://www.curseforge.com/minecraft/mc-mods/servercore/files/8312206
    https://www.curseforge.com/minecraft/mc-mods/zfastnoise/files/8519662
    https://www.curseforge.com/minecraft/mc-mods/spark/files/7815877
  MODRINTH_PROJECTS: |
    chunksmith:qQk6EqQA
