apiVersion: apps/v1
kind: Deployment
metadata:
  name: modded-mc
  namespace: game-servers
  annotations:
    reloader.stakater.com/auto: "true"
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: modded-mc
  template:
    metadata:
      labels:
        app: modded-mc
    spec:
      volumes:
        - name: modded-mc-pvc-again-again
          persistentVolumeClaim:
            claimName: modded-mc-pvc-again-again
      nodeSelector:
        kubernetes.io/hostname: s7
      containers:
        - name: modded-mc
          image: docker.io/itzg/minecraft-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "20Gi"
              cpu: "4"
            limits:
              memory: "24Gi"
              cpu: "6"
          ports:
            - containerPort: 25565
              protocol: TCP
              name: minecraft
            - containerPort: 9100
              protocol: TCP
              name: metrics
            - containerPort: 8100
              protocol: TCP
              name: map
          volumeMounts:
            - name: modded-mc-pvc-again-again
              mountPath: /data
          startupProbe:
            exec:
              command:
                - mc-monitor
                - status
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - mc-monitor
                - status
            initialDelaySeconds: 30
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: modded-mc-config-again-again
            - secretRef:
                name: modded-mc-secrets-again-again
