apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modded-mc-pvc-again-again
  namespace: game-servers
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
