apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: entertainment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: entertainment-content
          persistentVolumeClaim:
            claimName: entertainment-content-pvc
      containers:
        - name: lidarr
          image: ghcr.io/hotio/lidarr:release-2.7.1.4417
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8686
              name: http
              protocol: TCP
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Dublin"
            - name: UMASK
              value: "002"
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: entertainment-content
              mountPath: /data
          startupProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 5
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr-exporter
  namespace: entertainment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lidarr-exporter
  template:
    metadata:
      labels:
        app: lidarr-exporter
    spec:
      containers:
        - name: lidarr-exporter
          image: ghcr.io/onedr0p/exportarr:v2.0.1
          args:
            - lidarr
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://lidarr.entertainment.svc.cluster.local:8686"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: lidarr-exporter
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
