apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: entertainment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      volumes:
        - name: readarr-config
          persistentVolumeClaim:
            claimName: readarr-config
        - name: entertainment-content
          persistentVolumeClaim:
            claimName: entertainment-content-pvc
      containers:
        - name: readarr
          image: ghcr.io/hotio/readarr:testing-0.4.4.2686
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8787
              name: http
              protocol: TCP
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Dublin"
            - name: UMASK
              value: "002"
          volumeMounts:
            - name: readarr-config
              mountPath: /config
            - name: entertainment-content
              mountPath: /data
          startupProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 5
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-exporter
  namespace: entertainment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: readarr-exporter
  template:
    metadata:
      labels:
        app: readarr-exporter
    spec:
      containers:
        - name: readarr-exporter
          image: ghcr.io/onedr0p/exportarr:v2.1
          args:
            - readarr
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://readarr.entertainment.svc.cluster.local:8787"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: readarr-exporter
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
