apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hassio-media
  namespace: homeassistant
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
