apiVersion: v1
kind: ConfigMap
metadata:
  name: hassio-secrets-template
  namespace: homeassistant
data:
  secrets-template.yaml: |
    database_url: "${DATABASE_URL}"
    client_secret: "${CLIENT_SECRET}"
    client_id: "${CLIENT_ID}"
    zefir_words_discord_webhook_url: "${ZEFIR_WORDS_DISCORD_WEBHOOK_URL}"
    zefir_words_wordonly_discord_webhook_url: "${ZEFIR_WORDS_WORDONLY_DISCORD_WEBHOOK_URL}"
