apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx-exporter
  namespace: databases
  labels:
    app: emqx-exporter
spec:
  selector:
    matchLabels:
      app: emqx-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: emqx-exporter
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: exporter
          image: emqx/emqx-exporter:0.2.9
          imagePullPolicy: IfNotPresent
          args:
            - --emqx.nodes=emqx-dashboard.databases.svc.cluster.local:18083
            - --emqx.auth-username=$(EMQX_API_KEY)
            - --emqx.auth-password=$(EMQX_SECRET_KEY)
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          envFrom:
            - secretRef:
                name: emqx-exporter-secrets
          ports:
            - containerPort: 8085
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
