apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: cloudflare-ddns
          image: docker.io/favonia/cloudflare-ddns:1.15.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          env:
            - name: PROXIED
              value: "true"
            - name: IP6_PROVIDER
              value: none
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns-secrets
                  key: api-token
            - name: DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: cloudflare-ddns-config
                  key: domains
            - name: PROXIED
              valueFrom:
                configMapKeyRef:
                  name: cloudflare-ddns-config
                  key: proxied
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
