apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: entertainment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      volumes:
        - name: audiobookshelf-config
          nfs:
            server: 10.0.3.1
            path: /mnt/jabberwock
        - name: entertainment-content
          persistentVolumeClaim:
            claimName: entertainment-content-pvc
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.19.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: audiobookshelf-config
              mountPath: /config
              subPath: casaos/audiobookshelf/
            - name: entertainment-content
              mountPath: /data
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 5
            periodSeconds: 10
