"""Generate the committed worker ConfigMap without credentials or local state."""
from pathlib import Path

source = Path(__file__).with_name("xzz_sync.py")
target = Path(__file__).resolve().parents[2] / "k8s/productivity/boardripper/xzz-script.yml"
header = """# Generated by scripts/boardripper-xzz-sync/build_configmap.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: boardripper-xzz-sync-script
  namespace: productivity
data:
  xzz_sync.py: |
"""
target.write_text(header + "".join("    " + line + "\n" for line in source.read_text().splitlines()))
print(target)
