kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: papermc-data
  namespace: game-servers
spec:
  storageClassName: floof-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
