apiVersion: v1
kind: ConfigMap
metadata:
  name: part-db-configmap
  namespace: productivity
data:
  APP_ENV: docker
  DEFAULT_LANG: en
  DEFAULT_TIMEZONE: Europe/Dublin
  BASE_CURRENCY: EUR
  INSTANCE_NAME: "Zefir's Parts Collection"
  ALLOW_ATTACHMENT_DOWNLOADS: "1"
  USE_GRAVATAR: "1"
  TRUSTED_PROXIES: "127.0.0.0/8,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  MAX_ATTACHMENT_FILE_SIZE: "100M"
  CHECK_FOR_UPDATES: "0"
  HISTORY_SAVE_CHANGED_FIELDS: "true"
  HISTORY_SAVE_CHANGED_DATA: "true"
  HISTORY_SAVE_REMOVED_DATA: "true"
  EMAIL_SENDER_EMAIL: "noreply@zefirsroyal.cloud"
  EMAIL_SENDER_NAME: "Zefir's Parts Collection"
  SAML_BEHIND_PROXY: "1"
  SAML_ENABLED: "1"
  SAML_UPDATE_GROUP_ON_LOGIN: "1"
