apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: part-db-pvc
  namespace: productivity
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: floof-iscsi-csi
