apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoarder-meilisearch
  namespace: productivity
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: hoarder-meilisearch
  template:
    metadata:
      labels:
        app: hoarder-meilisearch
    spec:
      containers:
        - name: meilisearch
          image: docker.io/getmeili/meilisearch:v1.12.5
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: hoarder-secrets
                  key: MEILI_MASTER_KEY
          ports:
            - containerPort: 7700
              protocol: TCP
              name: http
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: hoarder-meilisearch
