apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: palworld
  name: palworld-data-2026-08-10
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
