apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  namespace: smarthome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
        app: homebox
    spec:
      containers:
        - name: homebox
          image: ghcr.io/sysadminsmedia/homebox:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: homebox-config
            - secretRef:
                name: homebox-secrets-infisical
          ports:
            - containerPort: 7745
              protocol: TCP
              name: http
