name: Rebuild Octoprint

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - k8s/octoprint/octoprint-image/*
      - k8s/octoprint/octoprint-image/**/*
      - .github/workflows/rebuild-octoprint.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Log into registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/brunostjohn/octoprint
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.13.0
        with:
          platforms: linux/amd64,linux/arm64
          context: k8s/octoprint/octoprint-image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
