apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: smarthome
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: docker.io/eclipse-mosquitto:2.0.22
          command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
